sc 04

diff --git a/.github/workflows/10-status-checks.yml b/.github/workflows/10-status-checks.yml
--- a/.github/workflows/10-status-checks.yml
+++ b/.github/workflows/10-status-checks.yml
@@ -8,7 +8,12 @@ jobs:
       - name: Build
         run: |
             echo "Running Build..."
-            exit 1
+            #exit 1
+
+      - name: Generate Error Report
+        if: failure()
+        run: |
+            echo "Running Generate Error Report..."
 
       - name: Unit Testing
         run: |
@@ -17,3 +22,5 @@ jobs:
       - name: Deployment
         run: |
             echo "Running Deployment"
+    
+
